'use client';
import { useState, useId, cloneElement, isValidElement, type ReactElement } from 'react';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Plus, Trash2, ArrowRight } from 'lucide-react';
import { Button } from './ui/button';
import { api, post, categories, datePlus } from '@/lib/api';

export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label>{isValidElement(children)?cloneElement(children as ReactElement<any>,{id,'aria-describedby':hint?id+'-hint':undefined}):children}{hint&&<small id={id+'-hint'}>{hint}</small>}</div>}
const resourceSchema=z.object({resource_type:z.string(),quantity:z.coerce.number().positive(),unit:z.string().min(1),specifications:z.string(),required_start:z.string().min(1),required_end:z.string().min(1),notes:z.string()});
const projectSchema=z.object({title:z.string().min(3),description:z.string().min(10),location:z.string().min(2),latitude:z.coerce.number().min(-90).max(90),longitude:z.coerce.number().min(-180).max(180),sdg:z.coerce.number().min(1).max(17),urgency:z.string(),start_date:z.string().min(1),end_date:z.string().min(1),expected_beneficiaries:z.coerce.number().int().nonnegative(),requirements:z.array(resourceSchema).min(1)});
type ProjectFields=z.infer<typeof projectSchema>;
const newNeed=()=>({resource_type:'Volunteers',quantity:20,unit:'people',specifications:'',required_start:datePlus(7),required_end:datePlus(35),notes:''});
export function ProjectForm({onSaved}:{onSaved:(id:number)=>void}){
 const [error,setError]=useState('');
 const {register,control,handleSubmit,formState:{errors,isSubmitting}}=useForm<ProjectFields>({resolver:zodResolver(projectSchema) as any,defaultValues:{title:'',description:'',location:'Hyderabad',latitude:17.385,longitude:78.486,sdg:4,urgency:'Medium',start_date:datePlus(7),end_date:datePlus(35),expected_beneficiaries:0,requirements:[newNeed()]}});
 const {fields,append,remove}=useFieldArray({control,name:'requirements'});
 return <form onSubmit={handleSubmit(async values=>{setError('');try{const p=await post('/projects',{...values,requirements:values.requirements.map(r=>({...r,specifications:r.specifications.split(',').map(s=>s.trim()).filter(Boolean)}))});onSaved(p.id)}catch(e){setError((e as Error).message)}})} className="form-stack">
 <section className="panel"><div className="section-heading"><span className="step">01</span><div><h2>Tell us about your project</h2><p>Give potential partners a clear picture of the need.</p></div></div>
 <Field label="Project title"><input {...register('title')} placeholder="e.g. Digital literacy for 120 young learners" required minLength={3}/></Field>
 <Field label="Description"><textarea {...register('description')} rows={4} placeholder="What will your project achieve, and how can partners help?" required minLength={10}/></Field>
 <div className="form-grid"><Field label="Primary SDG"><select {...register('sdg')}>{Array.from({length:17},(_,i)=><option key={i} value={i+1}>SDG {i+1}</option>)}</select></Field><Field label="Urgency"><select {...register('urgency')}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Start date"><input type="date" {...register('start_date')} required/></Field><Field label="End date"><input type="date" {...register('end_date')} required/></Field><Field label="Location"><input {...register('location')} required/></Field><Field label="Expected beneficiaries" hint="An estimate; never counted as verified people reached."><input type="number" min="0" {...register('expected_beneficiaries')}/></Field><Field label="Latitude"><input type="number" step="any" {...register('latitude')}/></Field><Field label="Longitude"><input type="number" step="any" {...register('longitude')}/></Field></div></section>
 <section className="panel"><div className="section-heading"><span className="step">02</span><div><h2>What resources do you need?</h2><p>Add a separate requirement for each resource and unit.</p></div></div>
 {fields.map((f,i)=><div className="requirement-form" key={f.id}><div className="row between"><h3>Requirement {i+1}</h3>{fields.length>1&&<Button type="button" variant="ghost" aria-label={`Remove requirement ${i+1}`} onClick={()=>remove(i)}><Trash2 size={16}/></Button>}</div><div className="form-grid"><Field label="Resource category"><select {...register(`requirements.${i}.resource_type`)}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Quantity"><input type="number" min="0.01" step="any" {...register(`requirements.${i}.quantity`)} required/></Field><Field label="Unit" hint="Funding: INR · Volunteers: people · Use identical units in offers."><input {...register(`requirements.${i}.unit`)} required/></Field><Field label="Mandatory skills / specifications" hint="Comma-separated exact tags, e.g. tutoring, laptop."><input {...register(`requirements.${i}.specifications`)}/></Field><Field label="Required from"><input type="date" {...register(`requirements.${i}.required_start`)} required/></Field><Field label="Required until"><input type="date" {...register(`requirements.${i}.required_end`)} required/></Field></div><Field label="Notes"><input {...register(`requirements.${i}.notes`)}/></Field></div>)}
 <Button variant="outline" type="button" onClick={()=>append(newNeed())}><Plus size={16}/> Add requirement</Button></section>
 {Object.keys(errors).length>0&&<div className="error" role="alert">Check required fields, positive quantities, and valid coordinates.</div>}{error&&<div className="error" role="alert">{error}</div>}
 <div className="row between"><p className="muted">Matching uses structured fields. No AI API is required.</p><Button disabled={isSubmitting}>{isSubmitting?'Creating…':'Create project'} <ArrowRight size={16}/></Button></div></form>
}

export function OfferForm({offer,onSaved,onCancel}:{offer?:any;onSaved:()=>void;onCancel:()=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);const data={resource_type:f.get('resource_type'),total_capacity:Number(f.get('total_capacity')),unit:f.get('unit'),specifications:String(f.get('specifications')).split(',').map(s=>s.trim()).filter(Boolean),available_start:f.get('available_start'),available_end:f.get('available_end'),location:f.get('location'),latitude:f.get('latitude')===''?null:Number(f.get('latitude')),longitude:f.get('longitude')===''?null:Number(f.get('longitude')),service_radius:Number(f.get('service_radius')),remote:f.get('remote')==='on',conditions:f.get('conditions'),status:f.get('status')};try{await api(offer?'/offers/'+offer.id:'/offers',{method:offer?'PUT':'POST',body:JSON.stringify(data)});onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form className="panel form-stack" onSubmit={submit}><h2>{offer?'Edit resource offer':'Create a resource offer'}</h2><div className="form-grid"><Field label="Resource category"><select name="resource_type" defaultValue={offer?.resource_type||'Funding'}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Total capacity"><input name="total_capacity" type="number" step="any" min="0.01" required defaultValue={offer?.total_capacity||30000}/></Field><Field label="Unit" hint="Funding: INR · Volunteers: people"><input name="unit" defaultValue={offer?.unit||'INR'} required/></Field><Field label="Skills / specifications (comma separated)"><input name="specifications" defaultValue={offer?.specifications?.join(', ')||''}/></Field><Field label="Available from"><input name="available_start" type="date" defaultValue={offer?.available_start||datePlus(0)} required/></Field><Field label="Available until"><input name="available_end" type="date" defaultValue={offer?.available_end||datePlus(90)} required/></Field><Field label="Location"><input name="location" defaultValue={offer?.location||'Hyderabad'} required/></Field><Field label="Service radius (km)"><input name="service_radius" type="number" min="0" defaultValue={offer?.service_radius??50}/></Field><Field label="Latitude"><input name="latitude" type="number" step="any" defaultValue={offer?.latitude??17.385}/></Field><Field label="Longitude"><input name="longitude" type="number" step="any" defaultValue={offer?.longitude??78.486}/></Field><Field label="Status"><select name="status" defaultValue={offer?.status||'active'}><option>active</option><option>inactive</option></select></Field><label className="check"><input name="remote" type="checkbox" defaultChecked={offer?.remote??true}/> Remote / location independent</label></div><Field label="Conditions"><textarea name="conditions" defaultValue={offer?.conditions||''} rows={2}/></Field>{error&&<p className="error" role="alert">{error}</p>}<div className="row"><Button disabled={busy}>{busy?'Saving…':'Save offer'}</Button><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button></div></form>
}

export function AuthForm({onSaved}:{onSaved:()=>void}){
 const [mode,setMode]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const role=f.get('role');const data=mode==='login'?{email:f.get('email'),password:f.get('password')}:{name:f.get('name'),email:f.get('email'),password:f.get('password'),role,organization:{name:f.get('organization'),organization_type:role==='ngo'?'ngo':f.get('type'),location:f.get('location'),supported_sdgs:[Number(f.get('sdg'))]}};try{await post('/auth/'+(mode==='login'?'login':'register'),data);onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Register organization</button></div><form onSubmit={submit} className="form-stack">{mode==='register'&&<><Field label="Your name"><input name="name" required minLength={2}/></Field><Field label="Organization name"><input name="organization" required minLength={2}/></Field><div className="form-grid"><Field label="Role"><select name="role"><option value="ngo">NGO organizer</option><option value="contributor">Contributor</option></select></Field><Field label="Contributor type"><select name="type"><option value="company">Company / CSR</option><option value="college">College / volunteer group</option><option value="supplier">Supplier / community partner</option></select></Field><Field label="Location"><input name="location" defaultValue="Hyderabad" required/></Field><Field label="Supported SDG"><input name="sdg" type="number" min="1" max="17" defaultValue="4" required/></Field></div></>}<Field label="Email"><input name="email" type="email" autoComplete="email" required/></Field><Field label="Password"><input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='register'?10:1} required/></Field>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</Button></form></section>
}
