import {test,expect} from '@playwright/test';
test('judge journey: proposed funding becomes committed and delivered',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');
 await page.getByRole('button',{name:/NGO organizer/}).click();
 await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
 await page.getByRole('link',{name:'Create new project'}).click();
 await page.getByLabel('Project title',{exact:true}).fill('Browser journey '+Date.now());
 await page.getByLabel('Description',{exact:true}).fill('A browser-tested community programme requiring funding and volunteer support.');
 await page.getByLabel('Resource category',{exact:true}).selectOption('Funding');
 await page.getByLabel('Quantity',{exact:true}).fill('100');
 await page.getByLabel('Unit',{exact:true}).fill('INR');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.getByRole('heading',{name:/Browser journey/})).toBeVisible();
 await page.getByRole('button',{name:'Find matching partners',exact:true}).click();
 const card=page.locator('.match-card').first();
 await expect(card).toContainText('Proposed: 100 INR');
 const organization=await card.locator('h3').innerText();
 await card.getByRole('button',{name:/Request partnership/}).click();
 await expect(card).toContainText('pending');
 await page.goto('/login');
 await page.locator('.demo-accounts button').filter({hasText:organization}).click();
 await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
 await page.goto('/partnerships');
 const request=page.locator('.partnership-list>.panel').filter({hasText:'Browser journey'}).first();
 await request.getByRole('button',{name:'Accept request'}).click();
 await expect(request).toContainText('accepted');
 await request.getByLabel('Cumulative delivered total (INR)').fill('60');
 await request.getByRole('button',{name:'Record delivery'}).click();
 await expect(request.locator('.partnership-values')).toContainText('60 INR');
 await page.reload();
 await expect(page.locator('.partnership-list>.panel').filter({hasText:'Browser journey'}).first()).toContainText('60 INR');
 await page.goto('/impact');
 await expect(page.getByRole('heading',{name:'Collective effort. Visible progress.'})).toBeVisible();
 expect(errors).toEqual([]);
});
test('mobile navigation and project filters',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.goto('/projects');
 await page.getByRole('button',{name:'Toggle navigation'}).click();
 await expect(page.getByRole('link',{name:'Impact dashboard',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Impact dashboard',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Collective effort. Visible progress.'})).toBeVisible();
 await page.goto('/projects');
 await page.getByLabel('Search projects').fill('Digital futures');
 await expect(page.locator('.project-card').first()).toContainText('Digital futures');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 expect(overflow).toBe(false);
});

test('contributor creates, edits and deactivates an offer',async({page})=>{
 await page.goto('/login');
 await page.getByRole('button',{name:/CSR contributor/}).click();
 await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
 await page.goto('/offers');
 await page.getByRole('button',{name:'Create offer',exact:true}).click();
 await page.getByLabel('Resource category',{exact:true}).selectOption('Other');
 await page.getByLabel('Total capacity',{exact:true}).fill('3');
 await page.getByLabel('Unit',{exact:true}).fill('boxes');
 const tag='browser-offer-'+Date.now();
 await page.getByLabel('Skills / specifications (comma separated)').fill(tag);
 await page.getByRole('button',{name:'Save offer'}).click();
 const card=page.locator('.offer-card').filter({hasText:tag});
 await expect(card).toContainText('3boxes available');
 await card.getByRole('button',{name:'Edit offer'}).click();
 await page.getByLabel('Total capacity',{exact:true}).fill('5');
 await page.getByRole('button',{name:'Save offer'}).click();
 await expect(card).toContainText('5boxes available');
 await card.getByRole('button',{name:'Deactivate',exact:true}).click();
 await expect(card.locator('.badge')).toHaveText('inactive');
});

test('NGO creates multiple needs and administrator reviews a profile',async({page})=>{
 await page.goto('/login');
 await page.getByRole('button',{name:/NGO organizer/}).click();
 await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
 await page.goto('/projects/new');
 const title='Browser multiple needs '+Date.now();
 await page.getByLabel('Project title',{exact:true}).fill(title);
 await page.getByLabel('Description',{exact:true}).fill('A functional test of a project with two different resource requirements.');
 await page.getByRole('button',{name:'Add requirement'}).click();
 await expect(page.getByLabel('Resource category',{exact:true})).toHaveCount(2);
 await page.getByLabel('Resource category',{exact:true}).nth(1).selectOption('Funding');
 await page.getByLabel('Unit',{exact:true}).nth(1).fill('INR');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.getByRole('heading',{name:title})).toBeVisible();
 await expect(page.locator('tbody tr')).toHaveCount(2);
 await page.goto('/login');
 await page.getByRole('button',{name:/Demo administrator/}).click();
 await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
 await page.goto('/admin');
 const review=page.getByRole('combobox',{name:'Verification for Udaan Learning Collective · Demo'});
 const initial=await review.inputValue();
 await review.selectOption(initial==='verified'?'pending':'verified');
 await expect(page.getByRole('status')).toContainText('Verification review recorded.');
 await review.selectOption(initial);
 await expect(review).toHaveValue(initial);
});
